set (PHANTOM_LIBWIN_DIR ${CMAKE_CURRENT_LIST_DIR})

set (source_all 
    w_control.c 
    vid_read.c 
    scr_getset.c 
    w_decor.c 
    ev_window.c 
    w_getset.c 
    w_create.c 
    w_scroll.c 
    ev_main.c 
    vid_write.c 
    ev_mouse.c 
    bmp_pbm.c 
    rgba_bitblt_bits.c 
    scr_repaint.c 
    rgba_const.c 
    w_move_z.c 
    w_dump.c 
    rect_cmp.c 
    ctl_button.c 
    rgba_scroll.c 
    w_bg_win.c 
    w_lock.c 
    ctl_getset.c 
    ev_wtty.c 
    ev_put.c 
    vid_blt_wrap.c 
    w_truetype.c 
    scr_zbuf.c 
    w_resize.c 
    w_draw.c 
    w_repaint.c 
    w_menu.c 
    utf8proc.c 
    scr_painter.c 
    w_taskbar.c 
    ctl_create.c 
    scr_mouse_onoff.c 
    vid_mouse_pointer.c 
    rgba_zbmove.c 
    ctl_scrollbar.c 
    w_move_xy.c 
    ctl_text_field.c 
    w_replicate.c 
    w_blt.c 
    w_box.c 
    w_font.c 
    w_event_client.c 
    w_event_title.c 
    w_order.c 
    rgba_ablend_bits.c 
    w_update.c 
    ev_util.c 
    rgba_hsb.c 
    resources/OpenSans-Light.ttf.c 
    resources/button_next_green_full_alpha_x65.png.c 
    resources/RobotoMono-ThinItalic.ttf.c 
    resources/win_decor_dl.png.c 
    resources/vanilla_cream_rollup.png.c 
    resources/menu_normal_center.png.c 
    resources/checkbox_round_on_a_x30.png.c 
    resources/toolbar_icon_calendar_normal.png.c 
    resources/RobotoMono-Italic.ttf.c 
    resources/toolbar_icon_calendar_hover.png.c 
    resources/task_button.png.c 
    resources/OpenSans-Bold.ttf.c 
    resources/button_prev_green_alpha_x65.png.c 
    resources/power_button_sm.png.c 
    resources/icon_heart.png.c 
    resources/scrollbar_orange_bar_right.png.c 
    resources/win_decor_ul.png.c 
    resources/OpenSans-SemiBoldItalic.ttf.c 
    resources/toolbar_icon_shell_pressed.png.c 
    resources/checkbox_square_on_a_x30.png.c 
    resources/scrollbar_orange_bar_middle.png.c 
    resources/toolbar_icon_settings_pressed.png.c 
    resources/rollup_pressed.png.c 
    resources/menu_selected_center.png.c 
    resources/slide_switch_alpha_v31_off.png.c 
    resources/toolbar_icon_calendar_selected.png.c 
    resources/icon_key.png.c 
    resources/close_pressed.png.c 
    resources/OpenSans-SemiBold.ttf.c 
    resources/button_prev_green_full_alpha_x65.png.c 
    resources/scrollbar_bed_right.png.c 
    resources/slide_switch_off.png.c 
    resources/vanilla_cream_close.png.c 
    resources/scrollbar_orange_bar_left.png.c 
    resources/scrollbar_bed_middle_narrow.png.c 
    resources/OpenSans-ExtraBoldItalic.ttf.c 
    resources/RobotoMono-Light.ttf.c 
    resources/button_normal_alpha_x98_abw.png.c 
    resources/start_button_hover.png.c 
    resources/RobotoMono-LightItalic.ttf.c 
    resources/icon_conversation.png.c 
    resources/button_pressed_alpha_x98.png.c 
    resources/toolbar_icon_debug_hover.png.c 
    resources/win_decor_dr.png.c 
    resources/menu_normal_left.png.c 
    resources/text_field_icon_x160.png.c 
    resources/title_brown.png.c 
    resources/RobotoMono-Medium.ttf.c 
    resources/RobotoMono-Bold.ttf.c 
    resources/button_next_green_alpha_x65.png.c 
    resources/title_selected.png.c 
    resources/checkbox_round_off_a_x30.png.c 
    resources/small_popup_note.png.c 
    resources/title_green.png.c 
    resources/button_prev_alpha_x82.png.c 
    resources/icon_settings.png.c 
    resources/slide_switch_alpha_v31_on.png.c 
    resources/power_button_pressed_sm.png.c 
    resources/scroll_bar_green_handle.png.c 
    resources/title_violet.png.c 
    resources/menu_selected_left.png.c 
    resources/scrollbar_green_bar_right.png.c 
    resources/pin.png.c 
    resources/win_decor_ur.png.c 
    resources/toolbar_icon_selected.png.c 
    resources/scrollbar_green_bar_left.png.c 
    resources/OpenSans-BoldItalic.ttf.c 
    resources/notification_green_button.png.c 
    resources/toolbar_icon_calendar_pressed.png.c 
    resources/scrollbar_bed_middle.png.c 
    resources/OpenSans-Regular.ttf.c 
    resources/toolbar_icon_settings_normal.png.c 
    resources/rollup.png.c 
    resources/toolbar_icon_settings_hover.png.c 
    resources/toolbar_icon_debug_normal.png.c 
    resources/menu_normal_right.png.c 
    resources/checkbox_square_off_a_x30.png.c 
    resources/toolbar_icon_shell_normal.png.c 
    resources/button_center_white_for_green_alpha_x169.png.c 
    resources/RobotoMono-Thin.ttf.c 
    resources/RobotoMono-Regular.ttf.c 
    resources/button_hover_alpha_x98.png.c 
    resources/title_deselected.png.c 
    resources/button_next_alpha_x82.png.c 
    resources/toolbar_icon_shell_selected.png.c 
    resources/start_button_selected_w_key.png.c 
    resources/toolbar_icon_settings_selected.png.c 
    resources/text_field_x200.png.c 
    resources/start_button_selected.png.c 
    resources/button_normal_alpha_x98.png.c 
    resources/OpenSans-ExtraBold.ttf.c 
    resources/OpenSans-Italic.ttf.c 
    resources/menu_selected_right.png.c 
    resources/button_pressed_alpha_x98_abw.png.c 
    resources/scrollbar_green_bar_middle.png.c 
    resources/RobotoMono-MediumItalic.ttf.c 
    resources/close.png.c 
    resources/icon_text.png.c 
    resources/button_hover_alpha_x98_abw.png.c 
    resources/vanilla_background.png.c 
    resources/win_decor_ljoin.png.c 
    resources/toolbar_icon_debug_pressed.png.c 
    resources/RobotoMono-BoldItalic.ttf.c 
    resources/icon_home.png.c 
    resources/win_decor_rjoin.png.c 
    resources/icon_plus.png.c 
    resources/OpenSans-LightItalic.ttf.c 
    resources/start_button_normal.png.c 
    resources/toolbar_icon_shell_hover.png.c 
    resources/slide_switch_on.png.c 
    resources/icon_screen.png.c 
    resources/scrollbar_bed_left.png.c 
    fonts/drv_video_kolibri2.fnt.c 
    fonts/drv_video_8x16san.fnt.c 
    fonts/drv_video_8x16cou.fnt.c 
    fonts/drv_video_16x16.fnt.c 
    fonts/freebsd_font.c 
    fonts/drv_video_8x16med.fnt.c 
    fonts/gallant12x22.c 
    fonts/drv_video_8x16bro.fnt.c 
    fonts/drv_video_8x16rom.fnt.c 
    fonts/drv_video_8x16scr.fnt.c 
    fonts/drv_video_kolibri1.fnt.c 
    fonts/drv_video_8x16ant.fnt.c 
    fonts/8x11.fnt.c 
    mice/default_mouse.c
)

# convert filenames to absolute paths
list(TRANSFORM source_all PREPEND ${PHANTOM_LIBWIN_DIR}/)

set (PHANTOM_LIBWIN_SOURCE ${source_all})
